name: tf-env

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow==1.13.1
    - tensorflow-gpu==1.13.1
    - keras==2.2.4
    - opencv-python
    - numpy
    - scipy
    - pip
    - Pillow
    - cython
    - matplotlib
    - scikit-image
    - h5py
    - imgaug
    - Ipython
    - pycocotools
    - ipykernel